server:
  port: 8084

spring:
  application:
    name: apixa-mapping-service
  datasource:
    url: jdbc:sqlite:./data/mapping.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  threads:
    virtual:
      enabled: true

apixa:
  service-name: apixa-mapping-service
