package com.apixa.report.render;

import com.apixa.report.model.GeneratedReport;
import com.fasterxml.jackson.databind.JsonNode;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

/**
 * Step 16 HTML rendering: one self-contained, printable research report.
 *
 * <p><b>Self-contained by construction.</b> All styling is inline in a single {@code <style>} block: no
 * CDN, no web font, no remote script, no image link. The document therefore renders identically offline
 * and prints cleanly on A4/Letter.
 *
 * <p>The renderer only <em>reads</em> the canonical report document. It never re-computes a verdict, a
 * count or a metric; a section marked {@code notProvided} is printed as such rather than as an empty
 * table or a favourable-looking blank.
 */
@Component
public class HtmlReportRenderer {

    public String render(GeneratedReport report) {
        JsonNode doc = report.document();
        StringBuilder h = new StringBuilder(65536);
        GeneratedReport.ReportMetadata m = report.metadata();

        h.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n")
                .append("<meta charset=\"utf-8\">\n")
                .append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
                .append("<title>").append(esc(m.title())).append("</title>\n")
                .append("<style>\n").append(css()).append("\n</style>\n</head>\n<body>\n");

        h.append("<header class=\"cover\">\n<h1>").append(esc(m.title())).append("</h1>\n")
                .append("<p class=\"subtitle\">APIXA security contract conformance report</p>\n")
                .append("<table class=\"meta\"><tbody>\n")
                .append(row("Report id", m.reportId()))
                .append(row("Generated at", m.generatedAt()))
                .append(row("Generated by", m.generator()))
                .append(row("Schema version", m.schemaVersion()))
                .append(row("Project id", m.projectId()))
                .append(row("API version", m.versionLabel()))
                .append(row("Analysis run id", m.analysisRunId()))
                .append(row("Contract id", m.contractId()))
                .append(row("Evidence set id", m.evidenceSetId()))
                .append(row("Benchmark id", m.benchmarkId()))
                .append("</tbody></table>\n<p class=\"note\">").append(esc(m.note())).append("</p>\n")
                .append("</header>\n");

        h.append("<section id=\"overview\"><h2>1. Report Overview</h2>\n")
                .append("<p>Sections supplied: ").append(esc(String.join(", ", m.suppliedSections()))).append("</p>\n")
                .append("<p>Sections not provided: ")
                .append(esc(m.notProvidedSections().isEmpty() ? "none"
                        : String.join(", ", m.notProvidedSections())))
                .append("</p>\n")
                .append(conformanceOverview(doc.path("conformance")))
                .append("</section>\n");

        identity(h, doc);
        contract(h, doc);
        sourceAnalysis(h, doc);
        mappings(h, doc);
        conformance(h, doc);
        evidence(h, doc);
        runtime(h, doc);
        impact(h, doc);
        benchmark(h, doc);
        limitations(h, doc);
        notes(h, doc);
        h.append("<footer><p>End of report - generated by ").append(esc(m.generator()))
                .append(" at ").append(esc(m.generatedAt())).append("</p></footer>\n</body>\n</html>\n");
        return h.toString();
    }

    private String conformanceOverview(JsonNode conformance) {
        JsonNode summary = conformance.path("summary");
        if (summary.isMissingNode()) {
            return "<p class=\"notprovided\">Conformance results were not provided for this report.</p>\n";
        }
        return "<h3>Conformance verdicts (as supplied)</h3>\n<table class=\"grid\">\n<thead><tr>"
                + "<th>Verdict</th><th>Count</th></tr></thead><tbody>\n"
                + rows(summary.path("byConformanceStatus"))
                + "</tbody></table>\n";
    }

    private void identity(StringBuilder h, JsonNode doc) {
        h.append("<section id=\"identity\"><h2>2. Project / API Version / Analysis Run</h2>\n");
        h.append(keyValues(doc.path("project"), "Project"));
        h.append(keyValues(doc.path("apiVersion"), "API version"));
        h.append(keyValues(doc.path("analysisRun"), "Analysis run"));
        h.append("</section>\n");
    }

    private void contract(StringBuilder h, JsonNode doc) {
        h.append("<section id=\"contract\"><h2>3. Contract Summary</h2>\n");
        JsonNode node = doc.path("contract");
        if (!node.path("provided").asBoolean()) { notProvided(h, "Contract"); return; }
        JsonNode c = node.path("contract");
        h.append("<table class=\"kv\"><tbody>\n")
                .append(row("Contract id", text(c, "contractId")))
                .append(row("Status", text(c, "status")))
                .append(row("OpenAPI version", text(c, "openapiVersion")))
                .append(row("Source file", text(c, "sourceFile")))
                .append(row("Title", text(c, "title")))
                .append(row("Endpoints", text(node.path("summary"), "endpointCount")))
                .append(row("Security schemes", text(node.path("summary"), "securitySchemeCount")))
                .append("</tbody></table>\n");
        JsonNode endpoints = c.path("endpoints");
        if (endpoints.isArray() && !endpoints.isEmpty()) {
            h.append("<h3>Contract endpoints</h3>\n<table class=\"grid\">\n<thead><tr>"
                    + "<th>Method</th><th>Path</th><th>Operation</th><th>Declared security</th>"
                    + "<th>JSON path</th></tr></thead><tbody>\n");
            for (JsonNode e : endpoints) {
                h.append("<tr><td class=\"mono\">").append(esc(text(e, "method"))).append("</td>")
                        .append("<td class=\"mono\">").append(esc(text(e, "path"))).append("</td>")
                        .append("<td class=\"mono\">").append(esc(text(e, "operationId"))).append("</td>")
                        .append("<td>").append(esc(policy(textNode(e, "expectedSecurity")))).append("</td>")
                        .append("<td class=\"mono small\">").append(esc(text(e, "jsonPath"))).append("</td></tr>\n");
            }
            h.append("</tbody></table>\n");
        }
        h.append("</section>\n");
    }

    private void sourceAnalysis(StringBuilder h, JsonNode doc) {
        h.append("<section id=\"source\"><h2>4. Source Analysis</h2>\n");
        JsonNode node = doc.path("sourceAnalysis");
        if (!node.path("provided").asBoolean()) { notProvided(h, "Source analysis"); return; }
        JsonNode s = node.path("sourceAnalysis");
        h.append("<table class=\"kv\"><tbody>\n")
                .append(row("Analysis type", text(s, "analysisType")))
                .append(row("Status", text(s, "status")))
                .append(row("Analyzed files", text(node.path("summary"), "analyzedFiles")))
                .append(row("Endpoints", text(node.path("summary"), "endpointCount")))
                .append(row("Security rules", text(node.path("summary"), "securityRuleCount")))
                .append(row("Unresolved rules", text(node.path("summary").path("notTranslatedRules"), "unresolved")))
                .append(row("Complex expressions", text(node.path("summary").path("notTranslatedRules"), "complexExpression")))
                .append("</tbody></table>\n");

        JsonNode rules = s.path("securityRules");
        if (rules.isArray() && !rules.isEmpty()) {
            h.append("<h3>Source security rules (Step 9)</h3>\n<table class=\"grid\">\n<thead><tr>"
                    + "<th>Scope</th><th>Operator</th><th>Path pattern</th><th>Roles</th>"
                    + "<th>File</th><th>Line</th></tr></thead><tbody>\n");
            for (JsonNode r : rules) {
                h.append("<tr><td>").append(esc(text(r, "scope"))).append("</td>")
                        .append("<td class=\"mono\">").append(esc(text(r, "operator"))).append("</td>")
                        .append("<td class=\"mono\">").append(esc(text(r, "pathPattern"))).append("</td>")
                        .append("<td class=\"mono\">").append(esc(list(r, "roles"))).append("</td>")
                        .append("<td class=\"mono small\">").append(esc(text(r, "file"))).append("</td>")
                        .append("<td>").append(esc(text(r, "lineStart"))).append("</td></tr>\n");
            }
            h.append("</tbody></table>\n");
        }
        h.append("</section>\n");
    }

    private void mappings(StringBuilder h, JsonNode doc) {
        h.append("<section id=\"mapping\"><h2>5. Endpoint Mapping</h2>\n");
        JsonNode node = doc.path("mappings");
        if (!node.path("provided").asBoolean()) { notProvided(h, "Endpoint mapping"); return; }
        h.append(rows(node.path("summary").path("byStatus")));
        JsonNode items = node.path("mappings");
        if (items.isArray() && !items.isEmpty()) {
            h.append("<table class=\"grid\">\n<thead><tr><th>Contract endpoint</th><th>Status</th>"
                    + "<th>Confidence</th><th>Implementation</th><th>Reason</th></tr></thead><tbody>\n");
            for (JsonNode m : items) {
                String impl = m.path("implementationClass").asText("");
                String method = m.path("implementationMethod").asText("");
                h.append("<tr><td class=\"mono\">").append(esc(text(m, "method"))).append(" ")
                        .append(esc(text(m, "path"))).append("</td>")
                        .append("<td class=\"mono\">").append(esc(text(m, "status"))).append("</td>")
                        .append("<td class=\"mono\">").append(esc(text(m, "confidence"))).append("</td>")
                        .append("<td class=\"mono small\">").append(esc(impl.isEmpty() ? "" : impl + "#" + method))
                        .append(esc(text(m, "implementationPath"))).append("</td>")
                        .append("<td>").append(esc(text(m, "reason"))).append("</td></tr>\n");
            }
            h.append("</tbody></table>\n");
        }
        h.append("</section>\n");
    }

    private void conformance(StringBuilder h, JsonNode doc) {
        h.append("<section id=\"conformance\"><h2>6. Security Conformance</h2>\n");
        JsonNode node = doc.path("conformance");
        if (!node.path("provided").asBoolean()) { notProvided(h, "Conformance results"); return; }
        JsonNode items = node.path("conformance");
        for (JsonNode c : items) {
            h.append("<article class=\"endpoint\">\n<h3 class=\"mono\">")
                    .append(esc(text(c, "contractMethod"))).append(" ").append(esc(text(c, "contractPath")))
                    .append("</h3>\n<table class=\"kv\">\n<tbody>\n")
                    .append(row("Mapping", text(c, "mappingStatus")))
                    .append(row("Expected security", policy(textNode(c, "expectedSecurity"))))
                    .append(row("Implemented security", policy(textNode(c, "implementedSecurity"))))
                    .append(row("Conformance", text(c, "conformanceStatus")))
                    .append(row("Reason", text(c, "reason")))
                    .append("</tbody></table>\n");
            JsonNode applied = c.path("appliedRule");
            if (!applied.isMissingNode()) {
                h.append("<p class=\"small\">Applied source rule: <span class=\"mono\">")
                        .append(esc(text(applied, "operator"))).append(" ")
                        .append(esc(text(applied, "pathPattern"))).append("</span>")
                        .append(esc(text(applied, "file"))).append(":").append(esc(text(applied, "lineStart")))
                        .append("</p>\n");
            }
            JsonNode codes = c.path("evidenceCodes");
            if (codes.isArray() && !codes.isEmpty()) {
                h.append("<p class=\"small\">Evidence: <span class=\"mono\">")
                        .append(esc(String.join(", ", toList(codes)))).append("</span></p>\n");
            }
            h.append("</article>\n");
        }
        h.append("</section>\n");
    }

    private void evidence(StringBuilder h, JsonNode doc) {
        h.append("<section id=\"evidence\"><h2>7. Evidence Traceability</h2>\n");
        JsonNode node = doc.path("evidence");
        if (!node.path("provided").asBoolean()) { notProvided(h, "Evidence"); return; }
        JsonNode e = node.path("evidence");
        h.append("<p class=\"chain\">Contract &rarr; Mapping &rarr; Source endpoint &rarr; "
                + "Source security &rarr; Conformance</p>\n");
        h.append("<table class=\"kv\"><tbody>\n")
                .append(row("Evidence set", text(e, "evidenceSetId")))
                .append(row("Items", text(node.path("summary"), "itemCount")))
                .append("</tbody></table>\n");
        JsonNode items = e.path("items");
        if (items.isArray() && !items.isEmpty()) {
            h.append("<table class=\"grid\">\n<thead><tr><th>Code</th><th>Type</th><th>Endpoint</th>"
                    + "<th>File / line</th><th>Rule</th><th>Path pattern</th><th>Related</th>"
                    + "</tr></thead><tbody>\n");
            for (JsonNode i : items) {
                h.append("<tr><td class=\"mono\">").append(esc(text(i, "evidenceCode"))).append("</td>")
                        .append("<td class=\"mono\">").append(esc(text(i, "sourceType"))).append("</td>")
                        .append("<td class=\"mono small\">").append(esc(text(i, "httpMethod"))).append(" ")
                        .append(esc(text(i, "endpointPath"))).append("</td>")
                        .append("<td class=\"mono small\">").append(esc(text(i, "file"))).append(":")
                        .append(esc(text(i, "lineStart"))).append("</td>")
                        .append("<td class=\"mono\">").append(esc(text(i, "ruleType"))).append("</td>")
                        .append("<td class=\"mono small\">").append(esc(text(i, "pathPattern"))).append("</td>")
                        .append("<td class=\"mono small\">").append(esc(list(i, "relatedEvidenceCodes")))
                        .append("</td></tr>\n");
            }
            h.append("</tbody></table>\n");
        }
        h.append("</section>\n");
    }

    private void runtime(StringBuilder h, JsonNode doc) {
        h.append("<section id=\"runtime\"><h2>8. Runtime Verification</h2>\n");
        JsonNode node = doc.path("runtime");
        if (!node.path("provided").asBoolean()) { notProvided(h, "Runtime verification"); return; }
        h.append("<p class=\"note\">Runtime values are observations of an executed request. "
                + "No conformance verdict is derived from them.</p>\n");
        JsonNode items = node.path("runtime");
        if (items.isArray()) {
            h.append("<table class=\"grid\">\n<thead><tr><th>Request</th><th>Observed status</th>"
                    + "<th>Execution status</th><th>Error</th><th>Observed at</th></tr></thead><tbody>\n");
            for (JsonNode r : items) {
                h.append("<tr><td class=\"mono small\">").append(esc(text(r, "method"))).append(" ")
                        .append(esc(text(r, "url"))).append("</td>")
                        .append("<td class=\"mono strong\">").append(esc(text(r, "observedStatusCode"))).append("</td>")
                        .append("<td class=\"mono\">").append(esc(text(r, "executionStatus"))).append("</td>")
                        .append("<td class=\"mono small\">").append(esc(text(r, "errorType"))).append("</td>")
                        .append("<td class=\"small\">").append(esc(text(r, "observedAt"))).append("</td></tr>\n");
            }
            h.append("</tbody></table>\n");
        }
        h.append("</section>\n");
    }

    private void impact(StringBuilder h, JsonNode doc) {
        h.append("<section id=\"impact\"><h2>9. Change Impact (V1 to V2)</h2>\n");
        JsonNode node = doc.path("impact");
        if (!node.path("provided").asBoolean()) { notProvided(h, "Change impact"); return; }
        JsonNode i = node.path("impact");
        h.append("<table class=\"kv\"><tbody>\n")
                .append(row("V1 version", text(i, "v1VersionId")))
                .append(row("V2 version", text(i, "v2VersionId")))
                .append(row("Impact records", text(node.path("summary"), "totalImpacts")))
                .append("</tbody></table>\n");
        JsonNode items = i.path("impacts");
        if (items.isArray() && !items.isEmpty()) {
            h.append("<table class=\"grid\">\n<thead><tr><th>Category</th><th>Endpoint</th>"
                    + "<th>V1</th><th>V2</th><th>Details</th><th>Evidence</th></tr></thead><tbody>\n");
            for (JsonNode r : items) {
                String v1 = firstNonBlank(text(r, "v1Summary"), text(r, "v1ConformanceStatus"),
                        text(r, "v1Path"), text(r, "v1ObservedStatusCode"), "");
                String v2 = firstNonBlank(text(r, "v2Summary"), text(r, "v2ConformanceStatus"),
                        text(r, "v2Path"), text(r, "v2ObservedStatusCode"), "");
                h.append("<tr><td class=\"mono strong\">").append(esc(text(r, "category"))).append("</td>")
                        .append("<td class=\"mono\">").append(esc(text(r, "method"))).append(" ")
                        .append(esc(text(r, "path"))).append("</td>")
                        .append("<td class=\"mono small\">").append(esc(v1)).append("</td>")
                        .append("<td class=\"mono small\">").append(esc(v2)).append("</td>")
                        .append("<td class=\"small\">").append(esc(text(r, "details"))).append("</td>")
                        .append("<td class=\"mono small\">").append(esc(list(r, "v1EvidenceCodes"))).append(" ")
                        .append(esc(list(r, "v2EvidenceCodes"))).append("</td></tr>\n");
            }
            h.append("</tbody></table>\n");
            h.append("<p class=\"note\">").append(esc(text(node.path("summary"), "note"))).append("</p>\n");
        }
        h.append("</section>\n");
    }

    private void benchmark(StringBuilder h, JsonNode doc) {
        h.append("<section id=\"benchmark\"><h2>10. Benchmark</h2>\n");
        JsonNode node = doc.path("benchmark");
        if (!node.path("provided").asBoolean()) { notProvided(h, "Benchmark"); return; }
        JsonNode b = node.path("benchmark");
        JsonNode s = node.path("summary");
        h.append("<table class=\"kv\"><tbody>\n")
                .append(row("Benchmark id", text(b, "benchmarkId")))
                .append(row("Status", text(b, "status")))
                .append(row("Total cases", text(s, "totalCases")))
                .append(row("Executed", text(s, "executedCases")))
                .append(row("Skipped", text(s, "skippedCases")))
                .append(row("Passed", text(s, "passedCases")))
                .append(row("Failed", text(s, "failedCases")))
                .append(row("Accuracy", text(s, "accuracy")))
                .append(row("Interpretation", text(s, "interpretation")))
                .append("</tbody></table>\n");

        JsonNode cm = s.path("conformanceMetrics");
        if (!cm.isMissingNode()) {
            h.append("<h3>Conformance classification metrics</h3>\n<table class=\"kv\"><tbody>\n")
                    .append(row("Accuracy", text(cm, "accuracy")))
                    .append(row("Precision", text(cm, "precision")))
                    .append(row("Recall", text(cm, "recall")))
                    .append(row("F1", text(cm, "f1")))
                    .append(row("Positive class", text(cm, "positiveClass")))
                    .append("</tbody></table>\n");
            JsonNode matrix = cm.path("confusionMatrix");
            if (!matrix.isMissingNode()) {
                h.append("<h3>Confusion matrix (expected rows x actual columns)</h3>\n")
                        .append(confusion(matrix));
            }
        }
        JsonNode cases = b.path("cases");
        if (cases.isArray() && !cases.isEmpty()) {
            h.append("<h3>Benchmark case results</h3>\n<table class=\"grid\">\n<thead><tr>"
                    + "<th>Case</th><th>Group</th><th>Status</th><th>Discrepancy</th>"
                    + "</tr></thead><tbody>\n");
            for (JsonNode c : cases) {
                h.append("<tr><td class=\"mono\">").append(esc(text(c, "caseId"))).append("</td>")
                        .append("<td class=\"mono small\">").append(esc(text(c, "group"))).append("</td>")
                        .append("<td class=\"mono ").append("PASSED".equals(text(c, "status")) ? "ok" : "bad")
                        .append("\">").append(esc(text(c, "status"))).append("</td>")
                        .append("<td class=\"small\">").append(esc(text(c, "discrepancy"))).append("</td></tr>\n");
            }
            h.append("</tbody></table>\n");
            h.append("<p class=\"note\">Negative controls such as CTRL-001 are shown with their real"
                    + " status. Benchmark metrics describe the controlled fixture population only.</p>\n");
        }
        h.append("</section>\n");
    }

    private void limitations(StringBuilder h, JsonNode doc) {
        h.append("<section id=\"limitations\"><h2>11. Limitations / Notes</h2>\n");
        JsonNode node = doc.path("limitations");
        if (!node.path("provided").asBoolean()) { notProvided(h, "Limitations"); return; }
        h.append("<ul class=\"limitations\">\n");
        for (String l : toList(node.path("limitations"))) {
            h.append("<li>").append(esc(l)).append("</li>\n");
        }
        h.append("</ul>\n</section>\n");
    }

    private void notes(StringBuilder h, JsonNode doc) {
        h.append("<section id=\"notes\"><h2>12. Report Notes</h2>\n<ul class=\"limitations\">\n")
                .append("<li>This report is a representation of results produced by earlier APIXA steps."
                        + " No analysis was re-run to produce it.</li>\n")
                .append("<li>Conformance, mapping, impact and benchmark values are shown exactly as"
                        + " supplied; the report does not modify, re-score or re-order them.</li>\n")
                .append("<li>Runtime entries are observations, not conformance verdicts.</li>\n")
                .append("<li>Credential-bearing headers are masked; no source file content is included."
                        + "</li>\n")
                .append("</ul>\n</section>\n");
    }

    private String confusion(JsonNode matrix) {
        List<String> cols = new ArrayList<>();
        matrix.fieldNames().forEachRemaining(cols::add);
        StringBuilder t = new StringBuilder("<table class=\"grid\"><thead><tr><th>expected \\\\ actual</th>");
        for (String col : cols) t.append("<th>").append(esc(col)).append("</th>");
        t.append("</tr></thead><tbody>\n");
        for (String rowName : cols) {
            t.append("<tr><th class=\"mono\">").append(esc(rowName)).append("</th>");
            JsonNode row = matrix.path(rowName);
            for (String col : cols) {
                t.append("<td class=\"mono\">").append(esc(text(row, col))).append("</td>");
            }
            t.append("</tr>\n");
        }
        return t.append("</tbody></table>\n").toString();
    }

    private String rows(JsonNode counts) {
        StringBuilder t = new StringBuilder("<table class=\"grid\"><thead><tr><th>Value</th><th>Count</th>"
                + "</tr></thead><tbody>\n");
        Iterator<Map.Entry<String, JsonNode>> it = counts.fields();
        while (it.hasNext()) {
            Map.Entry<String, JsonNode> e = it.next();
            t.append("<tr><td class=\"mono\">").append(esc(e.getKey())).append("</td><td class=\"mono\">")
                    .append(esc(e.getValue().asText())).append("</td></tr>\n");
        }
        return t.append("</tbody></table>\n").toString();
    }

    private String keyValues(JsonNode section, String label) {
        if (!section.path("provided").asBoolean()) {
            return "<h3>" + label + "</h3>\n<p class=\"notprovided\">Not provided.</p>\n";
        }
        JsonNode v = section.path(label.charAt(0) == 'A' ? "apiVersion" : sectionName(section, label));
        StringBuilder t = new StringBuilder("<h3>").append(label).append("</h3>\n<table class=\"kv\"><tbody>\n");
        v.fields().forEachRemaining(f -> t.append(row(f.getKey(), f.getValue().isValueNode()
                ? f.getValue().asText() : f.getValue().toString())));
        return t.append("</tbody></table>\n").toString();
    }

    private String sectionName(JsonNode section, String label) {
        // The child node inside a section is the payload; its name matches the section for objects
        // and is pluralised for lists, so it is discovered from the node itself.
        var names = new ArrayList<String>();
        section.fieldNames().forEachRemaining(names::add);
        for (String n : names) {
            if (!"provided".equals(n) && !"status".equals(n) && !"summary".equals(n)) return n;
        }
        return label;
    }

    private void notProvided(StringBuilder h, String what) {
        h.append("<p class=\"notprovided\">").append(esc(what))
                .append(" results were not provided for this report.</p>\n</section>\n");
    }

    private String policy(JsonNode p) {
        if (p == null || p.isMissingNode()) return "notProvided";
        if (p.path("unknown").asBoolean()) return "UNKNOWN";
        boolean permitAll = p.path("permitAll").asBoolean();
        String auth = text(p, "authentication");
        if (permitAll || "NONE".equals(auth)) return "PUBLIC (permitAll)";
        List<String> parts = new ArrayList<>();
        parts.add(auth == null ? "AUTHENTICATED" : auth);
        String roles = list(p, "roles");
        String authorities = list(p, "authorities");
        String scopes = list(p, "scopes");
        if (!roles.isBlank()) parts.add("roles " + roles);
        if (!authorities.isBlank()) parts.add("authorities " + authorities);
        if (!scopes.isBlank()) parts.add("scopes " + scopes);
        return String.join(" ", parts);
    }

    private String row(String label, Object value) {
        String v = value == null ? null : String.valueOf(value);
        if (v == null || v.isBlank()) return "";
        return "<tr><th>" + esc(label) + "</th><td>" + esc(v) + "</td></tr>\n";
    }

    private String text(JsonNode node, String field) {
        if (node == null || node.isMissingNode()) return null;
        JsonNode v = node.path(field);
        return v.isMissingNode() || v.isNull() ? null : v.asText();
    }

    private JsonNode textNode(JsonNode node, String field) {
        return node == null ? null : node.path(field);
    }

    private String list(JsonNode node, String field) {
        JsonNode v = node == null ? null : node.path(field);
        return v != null && v.isArray() && !v.isEmpty() ? String.join(", ", toList(v)) : "";
    }

    private List<String> toList(JsonNode array) {
        List<String> out = new ArrayList<>();
        if (array != null) array.forEach(n -> out.add(n.asText()));
        return out;
    }

    private String firstNonBlank(String... values) {
        for (String v : values) if (v != null && !v.isBlank()) return v;
        return "";
    }

    /** Escapes every value; the report therefore cannot inject markup from supplied data. */
    private String esc(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\"", "&quot;").replace("'", "&#39;");
    }

    private String css() {
        return """
                :root { color-scheme: light; }
                * { box-sizing: border-box; }
                body { font-family: "Segoe UI", "Helvetica Neue", Arial, sans-serif; font-size: 13px;
                       line-height: 1.5; color: #1b1f23; background: #ffffff; margin: 0 auto;
                       max-width: 1000px; padding: 28px 34px 48px; }
                h1 { font-size: 22px; margin: 0 0 4px; }
                h2 { font-size: 16px; margin: 30px 0 10px; padding-bottom: 5px;
                     border-bottom: 2px solid #d7dde3; }
                h3 { font-size: 13.5px; margin: 18px 0 7px; }
                .subtitle { color: #55606b; margin: 0 0 14px; }
                .cover { border-bottom: 1px solid #d7dde3; padding-bottom: 14px; }
                table { border-collapse: collapse; width: 100%; margin: 8px 0 14px; }
                th, td { border: 1px solid #c9d2da; padding: 5px 7px; text-align: left; vertical-align: top; }
                thead th { background: #eef2f6; }
                table.kv th { width: 210px; background: #f7f9fb; font-weight: 600; }
                .grid td, .grid th { font-size: 12px; }
                .mono { font-family: Consolas, "Courier New", monospace; }
                .small { font-size: 11px; }
                .strong { font-weight: 700; }
                .ok { color: #14532d; font-weight: 600; }
                .bad { color: #8a1c1c; font-weight: 700; }
                .note { color: #55606b; font-size: 11.5px; }
                .notprovided { color: #7a5b00; background: #fdf6e3; border: 1px solid #e8d9a8;
                               padding: 6px 9px; display: inline-block; }
                .chain { font-family: Consolas, monospace; background: #f2f5f8; padding: 7px 9px;
                         border-left: 3px solid #7d8b99; }
                .endpoint { border: 1px solid #d7dde3; border-left: 3px solid #4a6a8a;
                            padding: 8px 12px; margin: 10px 0; page-break-inside: avoid; }
                .limitations li { margin-bottom: 4px; }
                footer { margin-top: 28px; border-top: 1px solid #d7dde3; padding-top: 10px;
                         color: #55606b; font-size: 11.5px; }
                @media print {
                  body { max-width: none; padding: 0; font-size: 11px; }
                  h2 { page-break-after: avoid; }
                  .endpoint, table { page-break-inside: avoid; }
                  section { page-break-inside: auto; }
                }
                """;
    }
}