server:
  port: 8087

spring:
  application:
    name: apixa-runtime-service
  datasource:
    url: jdbc:sqlite:./data/runtime.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  threads:
    virtual:
      enabled: true

apixa:
  service-name: apixa-runtime-service
